version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  fastapi:
    build: .
    container_name: fastapi-app
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - .:/app

volumes:
  mongo_data:
